# Generated by Django 5.1.5 on 2025-04-23 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodehoraire')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salle')),
            ],
        ),
    ]
